@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Nov 11 04:50:04 +0200 2024
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim SenderTestModule_tb_time_impl -key {Post-Implementation:sim_1:Timing:SenderTestModule_tb} -tclbatch SenderTestModule_tb.tcl -view C:/Users/panag/Desktop/GitHub/Repositories/Vivado-Code/Lab2/lab2_optional/SenderTestModule_tb_time_impl.wcfg -view C:/Users/panag/Desktop/GitHub/Repositories/Vivado-Code/Lab2/lab2_optional/SenderTestModule_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
